CREATE TABLE IF NOT EXISTS vip (
    id SERIAL PRIMARY KEY,
    category TEXT DEFAULT NULL,
    login TEXT DEFAULT NULL, 
    profile TEXT DEFAULT NULL,
    token TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

