import type { Metadata } from "next";
import "./globals.css";
import { Layout } from "@/component/layout/layout";
import { ContextProvider } from "@/component/context/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen">
      <body
        style={{ scrollbarColor: "rgba(255, 255, 255, 0.1) transparent" }}
        className=" relative flex w-full h-full bg-gradient-to-bl from-gray-900 to-black"
      >
        <ContextProvider>
          <Layout>{children}</Layout>
        </ContextProvider>
      </body>
    </html>
  );
}
